CREATE TABLE IF NOT EXISTS projects (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_projects_branch ON projects(branch);
CREATE TABLE IF NOT EXISTS vessels (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_vessels_branch ON vessels(branch);
CREATE TABLE IF NOT EXISTS drydocks (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_drydocks_branch ON drydocks(branch);
CREATE TABLE IF NOT EXISTS dockSlots (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_dockSlots_branch ON dockSlots(branch);
CREATE TABLE IF NOT EXISTS inventory (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_inventory_branch ON inventory(branch);
CREATE TABLE IF NOT EXISTS movements (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_movements_branch ON movements(branch);
CREATE TABLE IF NOT EXISTS equipment (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_equipment_branch ON equipment(branch);
CREATE TABLE IF NOT EXISTS bookings (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_bookings_branch ON bookings(branch);
CREATE TABLE IF NOT EXISTS subcontractors (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_subcontractors_branch ON subcontractors(branch);
CREATE TABLE IF NOT EXISTS workOrders (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_workOrders_branch ON workOrders(branch);
CREATE TABLE IF NOT EXISTS termins (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_termins_branch ON termins(branch);
CREATE TABLE IF NOT EXISTS employees (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_employees_branch ON employees(branch);
CREATE TABLE IF NOT EXISTS invoices (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_invoices_branch ON invoices(branch);
CREATE TABLE IF NOT EXISTS payables (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_payables_branch ON payables(branch);
CREATE TABLE IF NOT EXISTS ncr (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_ncr_branch ON ncr(branch);
CREATE TABLE IF NOT EXISTS incidents (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_incidents_branch ON incidents(branch);
CREATE TABLE IF NOT EXISTS inspections (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_inspections_branch ON inspections(branch);
CREATE TABLE IF NOT EXISTS purchaseOrders (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_purchaseOrders_branch ON purchaseOrders(branch);
CREATE TABLE IF NOT EXISTS requisitions (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_requisitions_branch ON requisitions(branch);
CREATE TABLE IF NOT EXISTS vendors (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_vendors_branch ON vendors(branch);
CREATE TABLE IF NOT EXISTS quotations (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_quotations_branch ON quotations(branch);
CREATE TABLE IF NOT EXISTS clients (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_clients_branch ON clients(branch);
CREATE TABLE IF NOT EXISTS documents (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_documents_branch ON documents(branch);
CREATE TABLE IF NOT EXISTS surveys (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_surveys_branch ON surveys(branch);
CREATE TABLE IF NOT EXISTS activities (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_activities_branch ON activities(branch);
CREATE TABLE IF NOT EXISTS services (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_services_branch ON services(branch);
CREATE TABLE IF NOT EXISTS spareparts (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_spareparts_branch ON spareparts(branch);
CREATE TABLE IF NOT EXISTS boq (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_boq_branch ON boq(branch);
CREATE TABLE IF NOT EXISTS branches (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_branches_branch ON branches(branch);
CREATE TABLE IF NOT EXISTS attendance (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_attendance_branch ON attendance(branch);
CREATE TABLE IF NOT EXISTS payroll (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_payroll_branch ON payroll(branch);
CREATE TABLE IF NOT EXISTS taxPeriods (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_taxPeriods_branch ON taxPeriods(branch);
CREATE TABLE IF NOT EXISTS rfqs (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_rfqs_branch ON rfqs(branch);
CREATE TABLE IF NOT EXISTS changeOrders (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_changeOrders_branch ON changeOrders(branch);
CREATE TABLE IF NOT EXISTS risks (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_risks_branch ON risks(branch);
CREATE TABLE IF NOT EXISTS leaves (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_leaves_branch ON leaves(branch);
CREATE TABLE IF NOT EXISTS trainings (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_trainings_branch ON trainings(branch);
CREATE TABLE IF NOT EXISTS timesheets (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_timesheets_branch ON timesheets(branch);
CREATE TABLE IF NOT EXISTS drawings (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_drawings_branch ON drawings(branch);
CREATE TABLE IF NOT EXISTS toolbox (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_toolbox_branch ON toolbox(branch);
CREATE TABLE IF NOT EXISTS warranties (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_warranties_branch ON warranties(branch);
CREATE TABLE IF NOT EXISTS calibrations (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_calibrations_branch ON calibrations(branch);
CREATE TABLE IF NOT EXISTS communications (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_communications_branch ON communications(branch);
CREATE TABLE IF NOT EXISTS contracts (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_contracts_branch ON contracts(branch);
CREATE TABLE IF NOT EXISTS bast (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_bast_branch ON bast(branch);
CREATE TABLE IF NOT EXISTS trials (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_trials_branch ON trials(branch);
CREATE TABLE IF NOT EXISTS requests (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_requests_branch ON requests(branch);
CREATE TABLE IF NOT EXISTS clientPos (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_clientPos_branch ON clientPos(branch);
CREATE TABLE IF NOT EXISTS settings (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_settings_branch ON settings(branch);
CREATE TABLE IF NOT EXISTS coa (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_coa_branch ON coa(branch);
CREATE TABLE IF NOT EXISTS journals (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_journals_branch ON journals(branch);
CREATE TABLE IF NOT EXISTS assets (id TEXT PRIMARY KEY, branch TEXT, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_assets_branch ON assets(branch);
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, username TEXT UNIQUE, pass_hash TEXT NOT NULL, name TEXT NOT NULL, role TEXT NOT NULL, email TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS wbs_by_project (project_id TEXT PRIMARY KEY, data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS team_by_project (project_id TEXT PRIMARY KEY, data TEXT NOT NULL);
